### ISSUE TITLE
`EACCES: permission denied, mkdir '/home/runner' occurred on a self-hosted runner

### ISSUE THREAD

**Issue by superbrothers** [engineerd/setup-kind#13]
On a self-hosted runner, the following error occurred.

```
Run engineerd/setup-kind@v0.3.0
downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
##[error]EACCES: permission denied, mkdir '/home/runner'
```

**Comment by ehtishamwrp** [comment]
```
Modifying PATH
  Entries added to PATH to use selected Ruby:
    /Users/runner/hostedtoolcache/Ruby/2.7.2/x64/bin
Error: Error: EACCES: permission denied, mkdir '/Users/runner'
```
I am also facing the same issue while configuring custom ruby paths

**Comment by Aficionado45** [comment]
Error: mkdir: /Users/runner: Permission denied
Error: The process '/opt/homebrew/bin/bash' failed with exit code 1

Still facing the same error when using a self hosted github runner with arm64 architecture on running a simple set up python workflow
