### ISSUE TITLE
Add Path is deprecated

### ISSUE THREAD

**Issue by potiuk** [engineerd/setup-kind#28]
When we are using setup-kind in latest version we get warning about "add-path" being deprecated.

Apparently you are using core.addPath method which also uses it. 

Add Path was deprecated in https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ and will be removed soon, so I think you need to change the mechanism to the new mechanism:

The path should be added to the ${GITHUB_PATH} file instead as described in https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path :

```
echo "{path}" >> $GITHUB_PATH
```

**Comment by stefanprodan** [comment]
@radu-matei any news on this? Seems that updating actions/core should fix it #27

**Comment by alexellis** [comment]
I also got this error today:

```
Run engineerd/setup-kind@v0.4.0
7
downloading kind from https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
9
/bin/chmod +x /home/runner/work/_temp/e0399e89-4069-4a52-83f3-f7ecf6ad776e
10
Error: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
11
Executing kind with args create,cluster,--name,kind,--wait,300s
12
/opt/hostedtoolcache/kind/0.7.0/x64/kind create cluster --name kind --wait 300s
13
Creating cluster "kind" ...
14
 • Ensuring node image (kindest/node:v1.17.0) 🖼  ...
```

Is there anything we can do to help out with this?

**Comment by potiuk** [comment]
We  switched to our custom way of installing Kind via script :(

**Comment by stefanprodan** [comment]
> Error: The `add-path` command is deprecated and will be disabled on November 16th.

So seems that on the 16th who ever uses KinD will end up with a broken CI 😢  I've used this action in a dozen places, all FluxCD projects, Flagger and many others are affected. Has anyone made a fork @potiuk ?

**Comment by pst** [comment]
I looked into this myself for Kubestack's pipelines. There's a KinD action from the helm team https://github.com/helm/kind-action But I haven't tried it yet. Just found it the other day.

**Comment by radu-matei** [comment]
Apologies for missing this issue, I am looking into it and create a new release with the fix.

However, it looks like the action version will have to be explicitly updated by the user, unfortunately.

**Comment by radu-matei** [comment]
Created a [new release](https://github.com/engineerd/setup-kind/releases/tag/v0.5.0) which uses the updated `@actions/core` package.

Feel free to reopen if there is any issue related to this change.

Thanks!

**Comment by potiuk** [comment]
Thanks!
