### ISSUE TITLE
Question on Kustomize availability during kind setup in GH Actions

### ISSUE THREAD

**Issue by sriumcp** [engineerd/setup-kind#32]
When we set up kind in a GH Action workflow/job, it seems `kustomize` and `kubectl` CLIs also become available to subsequent steps in that job.

This is great. 

However, is there a reliable way to know the version of Kustomize / kubectl CLI that will be installed by the kind action?

**Comment by radu-matei** [comment]
I haven't found a way to reliably control the tool versions in GitHub action hosts - this is why I've been using https://github.com/engineerd/configurator to configure the tool version required.

Let me know if this helps.

**Comment by radu-matei** [comment]
I'll close this for now, but feel free to reopen if you feel this should be addressed in a different way by this action.

Thanks!
