### ISSUE TITLE
Export KUBECONFIG environment variable by default

### ISSUE THREAD

**Issue by radu-matei** [engineerd/setup-kind#4]
Currently, consumers of this action must export export `KUBECONFIG` manually before using the cluster.

TODO: use `core.exportVariable('KUBECONFIG', '<kind kubeconfig>');` to expose it.

**Comment by tamalsaha** [comment]
This is not necessary with Kind v0.6.1

**Comment by radu-matei** [comment]
Great catch, thanks!
Closing, since we have a release that defaults to Kind v0.6.1.

Thanks!
