### ISSUE TITLE
Auto delete cluster at the end of a job

### ISSUE THREAD

**Issue by tamalsaha** [engineerd/setup-kind#41]
We are using this inside self hosted runner. Currently this cluster will left as-is when the job completes. So, we have to cleanup the cluster using `kind delete`. It will be great if this action could  automatically cleanup the cluster at the end of the job using `post` command.

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post

Thanks!

**Comment by radu-matei** [comment]
This sounds like the good thing to do, especially for the self hosted runners.

I think the default behavior should continue to be the current one, and add an optional config to delete the cluster at the end.
What do you think?

**Comment by tamalsaha** [comment]
I think the default behavior should be to delete the cluster if it was created in this run. We have not faced this issue so far because we were using GH hosted runners. So, we always got a new fresh machine.

**Comment by kanakagrawal** [comment]
@radu-matei do you plan to implement this for v0.6.0? 
Also, can you tell when is v0.6.0 planned to be released?

**Comment by radu-matei** [comment]
Hey, @kanakagrawal,
I didn't have a release planned, but if you are interested in adding support for this, together with #47 would definitely be worth cutting a new release.
Let me know if you are interested in contributing this feature.

Thanks!

**Comment by kanakagrawal** [comment]
> Hey, @kanakagrawal, I didn't have a release planned, but if you are interested in adding support for this, together with #47 would definitely be worth cutting a new release. Let me know if you are interested in contributing this feature.
> 
> Thanks!

Sure! I can work on this and come up with a PR.
