### ISSUE TITLE
Stopped working on `ubuntu-latest`

### ISSUE THREAD

**Issue by leszko** [engineerd/setup-kind#42]
After the latest release of `ubuntu-latest`, the GH action version `v0.5.0` stopped working.

Here are some [logs](https://github.com/hazelcast-guides/kubernetes/runs/3161853418?check_suite_focus=true#step:3:26):
```
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.19.1) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.19.1) 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
 • Waiting ≤ 5m0s for control-plane = Ready ⏳  ...
 ✗ Waiting ≤ 5m0s for control-plane = Ready ⏳
 • WARNING: Timed out waiting for Ready ⚠️
```

**Comment by radu-matei** [comment]
Could you please manually set the latest version of Kind, then increase the time period before trying the cluster?
Have you tried newer Kubernetes versions?

**Comment by radu-matei** [comment]
Kubernetes 1.20.2 with Kind v0.10 sees the same timeout, but the cluster creation is ultimately successful - see https://github.com/krustlet/krustlet/pull/650/checks?check_run_id=3164027118

**Comment by tamalsaha** [comment]
Try kind `0.11.1` . I think we saw similar timeouts with kind 0.10.0 but fixed with v0.11.1 and newer version of node images.

**Comment by leszko** [comment]
`0.11.1` works fine. Thanks @tamalsaha

**Comment by ameydev** [comment]
> v0.11.1

We also faced the same issue but after updating the kind version to `v0.11.1` the issue seems to be resolved now. Thanks @tamalsaha

**Comment by radu-matei** [comment]
Thank you so much for the fix, it is now merged, and there will be a new release soon.
