### ISSUE TITLE
Document how to configure the local storage provisioner

### ISSUE THREAD

**Issue by radu-matei** [engineerd/setup-kind#5]
https://github.com/kubernetes-sigs/kind/issues/865 describes how to set up the host path and Rancher provisioners for local storage.

https://github.com/tamalsaha/github-action-demo contains complete examples for both of them.

We need to properly document how to use them.

cc @tamalsaha

**Comment by tamalsaha** [comment]
The next version (> v0.6.1) of Kind will have a default working solution. https://github.com/kubernetes-sigs/kind/issues/1151

**Comment by radu-matei** [comment]
This is excellent, thanks a lot for following-up!

**Comment by swiftdiaries** [comment]
I think this can be closed with the latest KinD and Action version, this is included by default

**Comment by radu-matei** [comment]
@swiftdiaries - does it mean you can create a PV without any prior configuration to kind? That would be great!

I would, however, like to test this before closing the issue, thanks!

**Comment by tamalsaha** [comment]
>  does it mean you can create a PV without any prior configuration to kind?

Yes, since v0.7.0 .

**Comment by radu-matei** [comment]
Closing, thanks for the confirmation.
