### ISSUE TITLE
How do I update kubectl?

### ISSUE THREAD

**Issue by tamalsaha** [engineerd/setup-kind#9]
It seems that setup-kind installs `kubectl`. Just looking at the code, I can't figure out how it is done. How can we update kubectl to latest version?

Also, can helm be pre-installed also?

**Comment by radu-matei** [comment]
This action does _not_ install `kubectl`- it comes preconfigured in the GitHub runners - see [this article for a list of software configured in runners.][https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners].

I think we _can_ configure the tools you mentioned as part of this action - however, have a look at this action that can configure such tools - https://github.com/engineerd/configurator.

Would it work for your scenarios?
Thanks!

**Comment by tamalsaha** [comment]
The article you shared says GitHub automatically bundles v1.16.3. That works for me.

`engineerd/configurator` also looks interesting. Thanks again!

**Comment by mmorel-35** [comment]
From what I have seen all other available actions on the github actions which are setting up KinD have an option to define kubectl version. Don't you think engineerd/setup-kind should also follow this pattern ?
