### ISSUE TITLE
Timeline for v0.6.0 release

### ISSUE THREAD

**Issue by kanakagrawal** [engineerd/setup-kind#95]
Hi,

When will the version v0.6.0 be available?

**Comment by mmorel-35** [comment]
Hi @radu-matei, any updates on the next release ? Don't hesitate to ask for help if you need.

**Comment by mmorel-35** [comment]
@radu-matei , when do you think you’ll be able to find the time ?
Thank you !

**Comment by dnephin** [comment]
The default kind version does not appear to work anymore (see #140). It would be great to tag a new release so that the default configuration is usable.

**Comment by radu-matei** [comment]
v0.6.0 has been released.
Let me know if you seen anything odd with the new release.


Thanks, and apologies for the late release.

**Comment by vrubezhny** [comment]
Hello!

It looks like v0.6.0 cannot be installed:

```
Download action repository 'engineerd/setup-kind@dfca6572a7497bbd1bb14e5ad473f8a1ba864ca6' (SHA:dfca6572a7497bbd1bb14e5ad473f8a1ba864ca6)
Error: Could not find file '/home/runner/work/_actions/_temp_234d8e75-890b-4[36](https://github.com/redhat-developer/vscode-openshift-tools/actions/runs/11445993267/job/31844342439?pr=4575#step:1:40)8-8753-3b50b6e9e7b1/_staging/engineerd-setup-kind-dfca657/node_modules/.bin/json5'.
```

Any idieas?

**Comment by RainbowMango** [comment]
Hi, hit the same issue at https://github.com/kubernetes-sigs/work-api/pull/46.
